workflows:
  iTunesStoreReplica-workflow:
    name: iTunes Store Replica
    scripts:
      - name: CICD Started
        script: echo "Welcome to your CICD set up"
      - name: Build iTunesStoreReplica
        script: xcodebuild build -project "iTunesStoreReplica.xcodeproj" -scheme "iTunesStoreReplica" CODE_SIGN_INDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
    publishing:
      email:
        recipients: 
          - halimammegwa@gmail.com